# Sets the website to use local javascript/css only.
local: "true"


# the preview server used. Leave as is.
host: 0.0.0.0

# the port where the preview is rendered. You can leave this as is
# unless you have other Jekyll builds using this same port that might
# cause conflicts. in that case, use another port such as 2001.
port: 4000



